package com.warmthdawn.justenoughdrags;

import com.warmthdawn.justenoughdrags.compact.Enables;
import com.warmthdawn.justenoughdrags.compact.HeiState;
import com.warmthdawn.justenoughdrags.compact.bm2.BMReflectionHelper;
import com.warmthdawn.justenoughdrags.compact.xnet.XNetReflectionHelper;
import com.warmthdawn.justenoughdrags.network.NetworkHandler;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkCheckHandler;
import net.minecraftforge.fml.relauncher.Side;
import org.apache.logging.log4j.Logger;

import java.util.Map;

@Mod(modid = JustEnoughDrags.MODID,
    name = JustEnoughDrags.NAME,
    version = JustEnoughDrags.VERSION,
    dependencies = "required-after:jei;required-after:mixinbooter;after:appliedenergistics2;after:enderio"
)
public class JustEnoughDrags {
    // Tags class is auto-generated by RetroFuturaGradle at build time from
    // tags.properties + gradle.properties. Values track gradle.properties so
    // there's a single source of truth for version/modid/name.
    public static final String MODID = Tags.MOD_ID;
    public static final String NAME = Tags.MOD_NAME;
    public static final String VERSION = Tags.VERSION;

    private static Logger logger;

    @Mod.Instance
    public static JustEnoughDrags INSTANCE;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();
        Enables.init();
        HeiState.detect();
        if (HeiState.isHei) {
            logger.info("HEI detected; HEI bookmark-panel ghost-drag is enabled.");
        }
        if(FMLCommonHandler.instance().getSide().isClient()) {
            BMReflectionHelper.init();
            XNetReflectionHelper.init();
        }
    }


    private boolean serverInstalled;

    public boolean isServerInstalled() {
        return serverInstalled;
    }

    @NetworkCheckHandler
    public boolean checkModLists(Map<String, String> modList, Side side) {
        if (side == Side.SERVER) {
            serverInstalled = modList.containsKey(MODID);
        }

        return true;
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        NetworkHandler.registerMessages(MODID);
    }
}
